from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_page, name="login_page"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout_page, name="logout_page"),
    path('add-cart/<item_uid>', views.add_cart, name='add_cart'),
    path('cart/', views.cart, name="cart"),
    path('apply-coupon/', views.apply_coupon, name="apply_coupon"),
    path('remove-coupon/', views.remove_coupon, name="remove_coupon"),
    path('remove_cart_items/<cart_item_uid>', views.remove_cart_items, name="remove_cart_items"),
    path('update-cart-item/<cart_item_uid>/', views.update_cart_item, name="update_cart_item"),
    path('orders/', views.orders, name='orders'),
    path('api/order-card/<order_uid>/', views.order_card, name='order_card'),
    path('api/check-order-updates/', views.check_order_updates, name='check_order_updates'),
    path('add-item/', views.add_item, name='add_item'),
    path('all-items/', views.all_items, name='all_items'),
    path('api/search-suggestions/', views.search_suggestions, name='search_suggestions'),
    path('delete-recipe/<item_uid>/', views.delete_item, name="delete_item"),
    path('update-recipe/<item_uid>/', views.update_item, name="update_item"),
    path('success/', views.success, name="success"),
    path('admin-dashboard/', views.admin_dashboard, name="admin_dashboard"),
    path('all-orders/', views.all_orders, name="all_orders"),
    path('export-orders-csv/', views.export_orders_csv, name="export_orders_csv"),
    path('toggle-favourite/<item_uid>/', views.toggle_favourite, name="toggle_favourite"),
    path('add-review/<item_uid>/', views.add_review, name="add_review"),
    path('update-order-status/<order_uid>/', views.update_order_status, name="update_order_status"),
    path('add-address/', views.add_address, name="add_address"),
    path('manage-addresses/', views.manage_addresses, name="manage_addresses"),
    path('profile/', views.profile, name="profile"),
    path('change-password/', views.change_password, name="change_password"),
]
