# Generated by Django 6.0.5 on 2026-06-28 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0016_favouriteitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('delivery_time', models.IntegerField(default=30, help_text='Delivery time in minutes')),
            ],
            options={
                'verbose_name_plural': 'Delivery Zones',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='prep_time',
            field=models.IntegerField(default=15, help_text='Preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='foodapp.deliveryzone'),
        ),
    ]
